[package]
name = "csaf"
description = "An implementation of the Common Security Advisory Framework (CSAF)"
keywords    = ["security", "advisory", "vulnerability"]
categories = ["parser-implementations"]
version = "0.3.1"
edition = "2018"
authors = ["Blake Johnson"]
license = "MIT"
repository = "https://github.com/voteblake/csaf-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
url = { version = "2.x", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
cvss = { version = "1.x", features = ["serde"] }
rustsec = "0.24"
crates-index = "0.17"

[dev-dependencies]
serde_json = "1.0"
